name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: pip install uv

      - name: Run ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: check .

      - name: Install dependencies
        run: uv pip install --system
        continue-on-error: true

      # uv build leaves the resutls in the dist/ directory, we get two files:
      #   dist\slack_clients-0.1.0.tar.gz
      #   dist\slack_clients-0.1.0-py3-none-any.whl

      # - name: uv build
      #   run: uv build

      # - name: Run tests
      #   run: |
      #     if [ -f "pytest.ini" ] || [ -d "tests" ]; then
      #       pip install pytest
      #       pytest
      #     else
      #       echo "No tests found."
      #     fi

