name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv pip install --system
        continue-on-error: true

      - name: uv build
        run: uv build

      - name: Show working directory contents
        run: ls -alh

      # - name: Run tests
      #   run: |
      #     if [ -f "pytest.ini" ] || [ -d "tests" ]; then
      #       pip install pytest
      #       pytest
      #     else
      #       echo "No tests found."
      #     fi

